baseURL = "https://zerogenlab.github.io/" 
# baseURL = "http://localhost:1313/"
canonifyURLs = true
relativeURLs = false
title = "ZeroGen Lab"
author = "ZGL-Zhou Zhuhan"
languageCode = "en"
DefaultContentLanguage = "en"
defaultContentLanguageInSubdir = false
enableInlineShortcodes = true
theme = "tella"
enableRobotsTXT = true

# Please enable this feature if the site is available in Japanese, Chinese or Korean.
# If you're using Google Analytics, you can enable this feature.
#googleAnalytics = "UA-12345678-1"

# Disqus Comment System
#disqusShortname = ""

[params]

  showBlog = true
  mainSections = ['blog']
  subtitle = 'The Best Widgets on Earth'

  googleFonts = true

  [params.logo]
    main = "img/logo/logo.svg"
    alt = "ZeroGen Lab Logo"

    # The size parameter is the class name of tailwindcss
    # https://tailwindcss.com/
    size = "h-14"

  [params.site]
    name = "ZeroGen Lab"

  [params.icon]
    #If you want to use FontAwesome, set this parameter to true.
    fontawesome = true

  [params.homepage_meta_tags]
    meta_description = "ZeroGen Lab:Exploring GenAI with a from-zero mindset."
    meta_og_title = "ZeroGen Lab"
    meta_og_type = "website"
    meta_og_url = "https://zerogenlab.github.io/"
    meta_og_image = "https://zerogenlab.github.io/img/logo/ZEROGENLAB_LOGO.png"
    meta_og_description = "ZeroGen Lab:Exploring GenAI with a from-zero mindset."


[menu]

[[menu.main]]
  identifier = "home"
  name = "Home"
  url = "/"
  weight = 1

[[menu.main]]
  identifier = "members"
  name = "Members"
  url = "/members/"
  weight = 2

[[menu.main]]
  name = "Publications"
  url = "/research/publications/"
  weight = 4

[[menu.main]]
  name = "Projects"
  url = "/research/projects/"
  weight = 5

[[menu.main]]
  name = "Teaching"
  identifier = "teaching"
  weight = 6

[[menu.main]]
  parent = "teaching"
  name = "Machine Learning"
  url = "https://dasellmg.yuque.com/org-wiki-dasellmg-vsl5wg/ml2025"
  weight = 1

[[menu.main]]
  parent = "teaching"
  name = "AI Theory & Methods"
  url = "https://dasellmg.yuque.com/org-wiki-dasellmg-vsl5wg/aitm-2025"
  weight = 2

[[menu.main]]
  parent = "teaching"
  name = "LM from Scratch"
  url = "https://dasellmg.yuque.com/org-wiki-dasellmg-vsl5wg/lmfs2025"
  weight = 3

[[menu.main]]
  identifier = "coideas"
  name = "CoIdeas.Me"
  url = "https://coideas.me"
  weight = 7

[[menu.main]]
  identifier = "about"
  name = "About Us"
  url = "/about/"
  weight = 8

[[menu.footer]]
    name = "Home"
    url = "/"
    weight = 1

[outputFormats]
  [outputFormats.SearchIndex]
    mediaType = "application/json"
    baseName = "search"
    isPlainText = true
    notAlternative = true

[outputs]
  home = ["HTML", "SearchIndex"]



